version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: latest
    commands:
        - echo Installing source NPM dependencies...
        - NPM install
        - npm install -g @angular/cli
  build:
    commands:
        - echo node --version
        - echo Build started 
        - ng build --configuration production
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes